<?php
/**
 * Copyright © Ulmod. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php 
/**
 * Slider items template
 *
 * @var $block \Ulmod\Productslider\Block\Slider\Items
 */ 
?>
<?php use Magento\Framework\App\Action\Action; ?>
<?php 
$_items = $block->getSliderProductsCollection();

$sliderId = $block->getSliderDisplayId(); 

// slider config 
$slider = $block->getSlider();
$templateType = $slider->getTemplateType();
$showWishlist = $slider->getDisplayWishlist();
$showCompare = $slider->getDisplayCompare(); 
$showCart = $slider->getDisplayCart(); 
$enableAjaxcart = $slider->getEnableAjaxcart(); 
$navigation_enable = $slider->getNavigationEnable();
$pagination_enable = $slider->getPaginationEnable(); 

$image = 'category_page_grid'; 
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW; 
$viewMode = 'grid';
$class = $slider->getType(); 
$type = "";
?>
<?php if (count($_items) == 0) : ?>
	<p class="message note"><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></p>	
<?php else :?>
	<div class="um-prodslider block slider-type-<?= $block->escapeHtml($class); ?> 
		um-prodslider-t-<?= $block->escapeHtml($slider->getTemplateType())?>"
			<?= $slider->getRtl() ? 'dir="rtl" ' : "" ?> >
		<?php if ($slider->getDisplayTitle()) : ?>
		<div class="title-block">
		 <h2 id="block-<?= $block->escapeHtml($class) ?>-heading" role="heading" aria-level="2">
			<?= $block->escapeHtml($slider->getTitle()) ?>
		 </h2>
		 <div class="small-divider"></div>
		 <p class="um-info"> <?= $block->escapeHtml($slider->getDescription()) ?></p>
		</div>
		<?php endif ?>
	  <div class="content-block slider-list template-type-<?= $block->escapeHtml($slider->getTemplateType()) ?>"
		aria-labelledby="block-<?= $block->escapeHtml($class) ?>-heading">
		<?php if (!empty($_items)) : ?>
		<div class="products wrapper grid products-grid products-<?= $block->escapeHtml($type); ?>">
		<ol class="products list items product-slider<?= $block->escapeHtml($sliderId) ?>">
		<?php foreach ($_items as $collection) : ?>
		<?php $iterator = 1; ?>
		<?php foreach ($collection as $_item) : ?>

		<?= ($iterator++ == 1)
		  ? '<li class="item product um-product-item">' : '</li><li class="item product um-product-item">' ?>
		<div class="um-product-item-info product-item-info<?= $slider->getGrid() ? '' : '-'. $block->escapeHtml($class) ?>">
		<a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" 
		class="product photo product-item-photo">
			<?= $block->getImage($_item, $image)->toHtml(); ?>
		</a>
		<div class="product details product-item-details">
		  <strong class="product name product-item-name"><a class="product-item-link" 
			title="<?= $block->escapeHtml($_item->getName()) ?>" 
			href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
				<?= $block->escapeHtml($_item->getName()) ?></a>
		  </strong>
			<?php if ($slider->getDisplayPrice()) : ?>
				<?= /* @noEscape */ $block->getProductPrice($_item); ?>
			<?php endif ?>
			<?php if ($templateType) : ?>
				<?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
			<?php endif; ?>

			<?= $block->getProductsliderProductDetailsHtml($_item); ?>

		<?php if ($showWishlist || $showCompare || $showCart) : ?>
		<div class="um-product-item-inner">
		 <div class="product actions product-item-actions">
			<?php if ($showCart) : ?>
		 <div class="actions-primary">
			<?php if ($_item->isSaleable()) : ?>
			<?php if ($enableAjaxcart) : ?>
				<?php $postParams = $block->getAddToCartPostParams($_item); ?>
			<form data-role="tocart-form" 
				  action="<?= $block->escapeUrl($postParams['action']); ?>" 
				  method="post">
				<input type="hidden" name="product" 
					   value="<?= /* @noEscape */ $postParams['data']['product']; ?>">
				<input type="hidden" 
					  name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED; ?>"
				 value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
					<?= $block->getBlockHtml('formkey')?>
				<button type="submit"
						title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
						class="action tocart primary">
					<span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
				</button>
			</form>
			<?php else : ?>
				<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) : ?>
				<button class="action tocart primary" 
				` data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' 
				   type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
					<span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
				</button>
				<?php else : ?>
				<button class="action tocart primary" data-post='<?= /* @noEscape */ $block->getAddCartPostParams($_item); ?>'
						type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
					<span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
				</button>
				<?php endif; ?>
			<?php endif; ?>
			<?php else : ?>
				<?php if ($_item->getIsSalable()) : ?>
				<div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
				<?php else : ?>
				<div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
				<?php endif; ?>
			<?php endif; ?>
		  </div>
		<?php endif; ?>

		<?php if ($showWishlist || $showCompare) : ?>
		  <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
				<?php if ($block->isWishlistAllowed() && $showWishlist) : ?>
				  <a href="#" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item); ?>'
					   class="action towishlist" data-action="add-to-wishlist" 
					   title="<?= $block->escapeHtml(__('Add to Wish List')) ?>">
					   <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
				  </a>
				<?php endif; ?>
				<?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
				  <a href="#" class="action tocompare"
					 data-post='<?= /* @noEscape */ $block->getComparePostDataParams($_item);?>'
					 data-role="add-to-links"
					 title="<?= $block->escapeHtml(__('Add to Compare')); ?>">
					  <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
				  </a>
				<?php endif; ?>
		  </div>
		<?php endif; ?>
	  </div>
	</div> 
	<?php endif; ?>
	</div>
	</div>
	<?=($iterator == count($collection)+1) ? '</li>' : '' ?>
	<?php endforeach ?>
	<?php endforeach ?>
	</ol>
	</div>
	<?php endif ?>
	</div>
	</div>
    <script type="text/x-magento-init">
        {
        "*": 
            {
                "<?= $block->escapeHtml($block->getSliderType($slider)) ?>": {				
                    "sliderId": <?= $block->escapeHtml($sliderId) ?>,
                    "dots": <?= $block->escapeHtml(var_export((bool)$pagination_enable)) ?>,
                    "infinite": <?= $block->escapeHtml(var_export((bool)$slider->getInfinite())) ?>,
                    "slidesToShow": <?= $block->escapeHtml($slider->getSlidesToShow()) ?>,
                    "slidesToScroll": <?= $block->escapeHtml($slider->getSlidesToScroll()) ?>,
                    "speed": <?= $block->escapeHtml($slider->getSpeed()) ?>,
                    "autoplay": <?= $block->escapeHtml(var_export((bool)$slider->getAutoplay())) ?>,
                    "autoplaySpeed": <?= $block->escapeHtml($slider->getAutoplaySpeed()) ?>,
                    "rtl": <?= $block->escapeHtml(var_export((bool)$slider->getRtl())) ?>,	
                    "breakpointLarge": <?= $block->escapeHtml($slider->getBreakpointLarge()) ?>,	
                    "largeSlidesToShow": <?= $block->escapeHtml($slider->getLargeSlidesToShow()) ?>,	
                    "largeSlidesToScroll": <?= $block->escapeHtml($slider->getLargeSlidesToScroll()) ?>,	
                    "breakpointMedium": <?= $block->escapeHtml($slider->getBreakpointMedium()) ?>,	
                    "mediumSlidesToShow": <?= $block->escapeHtml($slider->getMediumSlidesToShow()) ?>,	
                    "mediumSlidesToScroll": <?= $block->escapeHtml($slider->getMediumSlidesToScroll()) ?>,
                    "breakpointSmall": <?= $block->escapeHtml($slider->getBreakpointSmall()) ?>,	
                    "smallSlidesToShow": <?= $block->escapeHtml($slider->getSmallSlidesToShow()) ?>,	
                    "smallSlidesToScroll": <?= $block->escapeHtml($slider->getSmallSlidesToScroll()) ?>,						
                    "nav": <?= $block->escapeHtml(var_export((bool)$navigation_enable)) ?>	
                }
            }
        }
    </script>
<?php endif ?>